### ISSUE TITLE
IAM Policy

### ISSUE THREAD

**Issue by Lusitaniae** [orzarchi/terraform-aws-cloudflare-security-group#6]
We could document the required IAM policy to deploy all the resources

**Comment by orzarchi** [comment]
Are you aware of any tool that looks at a TF module and generates required IAM permissions?
In my experience TF is usually applied with an admin account in an automated process

**Comment by Lusitaniae** [comment]
I usually do the same, but the CI/CD account was missing a few permissions that came up using this role, hence my request

There's a few tools but I haven't used it nor looked into integrating it with Terraform

I guess admin account is the answer, given the very different things Terraform could be deploying, not only regarding this module

**Comment by antigenius0910** [comment]
@Lusitaniae here you go

I create a new IAM user and grant it all permission then after it finish the terraform apply I go check event history from cloud trial so now I have all the IAM permission you need in order to run this module


Event source | Event name
-- | --
ec2.amazonaws.com | DescribeAccountAttributes
ec2.amazonaws.com | DescribeSecurityGroups
ec2.amazonaws.com | RevokeSecurityGroupEgress
events.amazonaws.com | DeleteRule
events.amazonaws.com | DescribeRule
events.amazonaws.com | ListTagsForResource
events.amazonaws.com | ListTargetsByRule
events.amazonaws.com | PutTargets
events.amazonaws.com | RemoveTargets
iam.amazonaws.com | DeletePolicy
iam.amazonaws.com | DeleteRole
iam.amazonaws.com | DetachRolePolicy
iam.amazonaws.com | GetPolicy
iam.amazonaws.com | GetPolicyVersion
iam.amazonaws.com | GetRole
iam.amazonaws.com | ListAttachedRolePolicies
iam.amazonaws.com | ListInstanceProfilesForRole
iam.amazonaws.com | ListPolicyVersions
iam.amazonaws.com | ListRolePolicies
lambda.amazonaws.com | AddPermission20150331v2
lambda.amazonaws.com | DeleteFunction20150331
lambda.amazonaws.com | GetFunction20150331v2
lambda.amazonaws.com | GetFunctionCodeSigningConfig
lambda.amazonaws.com | GetPolicy20150331v2
lambda.amazonaws.com | ListVersionsByFunction20150331
lambda.amazonaws.com | RemovePermission20150331v2
logs.amazonaws.com | DeleteLogGroup
logs.amazonaws.com | DescribeLogGroups
logs.amazonaws.com | ListTagsLogGroup

**Comment by Lusitaniae** [comment]
appreciated!

over the top
